env:
  DOCKER_COMPOSE_VERSION: 1.7.1
sudo: required
language: python
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - docker pull ebmdatalab/openprescribing-base:latest
  - docker pull mdillon/postgis:latest
cache:
  directories:
    - docker
services:
  - docker
script:
  - docker-compose run test
notifications:
  email:
    - tech@ebmdatalab.net