---
- name: A play for installing locally, used for testing tasks in Travis
  hosts: 127.0.0.1
  connection: local
  roles:
    - roles/setup
    - roles/app
  vars:
    checkout_path: /openprescribing
    virtualenv_path: "{{ checkout_path }}/venv"
    project_root_path: "{{ checkout_path }}/openprescribing"
    requirements_path: "{{ checkout_path }}/requirements.txt"
    log_path: "{{ checkout_path }}/logs"
  vars_files:
   - vars.yaml
  tasks:
    - name: Add the vagrant user
      user:
        name: "{{ USER }}"
        shell: /bin/bash
        state: present
