---
- name: A play for installing locally, used for testing tasks in Travis
  hosts: 127.0.0.1
  connection: local
  roles:
    - roles/setup
    - roles/app
  vars:
    repo_root: /openprescribing
    virtualenv_path: "{{ repo_root }}/venv"
    apps_root: "{{ repo_root }}/openprescribing"
    requirements_path: "{{ repo_root }}/requirements.txt"
    log_path: "{{ repo_root }}/logs"
  vars_files:
   - vars.yaml
  tasks:
    - name: Add the vagrant user
      user:
        name: "{{ USER }}"
        shell: /bin/bash
        state: present
