---
- name: A play for installing locally, used for testing tasks in Travis
  # The following two variables mean the app is installed directly in
  # the Travis environment, as opposed to the default which installs
  # over SSH to a remote host
  hosts: 127.0.0.1
  connection: local
  roles:
    - roles/setup
    - roles/app
  vars_files:
   - vars.yaml
  tasks:
    - name: Add the vagrant user
      user:
        name: "{{ USER }}"
        shell: /bin/bash
        state: present
