---
- hosts: all
  pre_tasks:
  - name: 'install python2'
    raw: sudo apt-get -y install python-simplejson
  roles:
    - roles/setup
    - roles/app
  vars:
    repo_root: /openprescribing
    virtualenv_path: "{{ repo_root }}/venv"
    apps_root: "{{ repo_root }}/openprescribing"
    requirements_path: "{{ repo_root }}/requirements.txt"
    log_path: "{{ repo_root }}/logs"
  vars_files:
   - vars.yaml
