---
USER: vagrant
HOME: "/home/{{ USER }}"
checkout_path: /code/openprescribing
virtualenv_path: "{{ checkout_path }}/venv"
project_root_path: "{{ checkout_path }}/openprescribing"
requirements_path: "{{ checkout_path }}/requirements.txt"
db_user: dev
db_password: sdkjasdalskdax
db_name: openprescribing_dev
log_path: /code/openprescribing/logs
secret_key: sdjfhasiufqpiasln
envvars:
  - var: DB_NAME
    name: DB_NAME
    content: "{{ db_name }}"
  - var: DB_USER
    name: DB_USER
    content: "{{ db_user }}"
  - var: DB_PASS
    name: DB_PASS
    content: "{{ db_password }}"
  - var: DB_HOST
    name: DB_HOST
    content: "localhost"
  - var: SECRET_KEY
    name: SECRET_KEY
    content: "{{ secret_key }}"
